### ISSUE TITLE
Future of project?

### ISSUE THREAD

**Issue by ebrassel** [annamichelle/LightboxGallery#4]
Thanks so much for providing this plugin! It's really great. We'd like to use it for an upcoming project, and I just wanted to ask whether you're still actively maintaining it? I noticed that the code hasn't been updated for a couple of years. No problems to report, just wondering if you plan to make revisions if future changes to Omeka require them. Thanks again!

**Comment by annamichelle** [comment]
Hi @ebrassel. So sorry for the late response. I'm glad you find this useful! I haven't been using Omeka (or coding much) lately. I don't have plans to keep this up to date at the time being. Please feel free to take it and make it your own!
